### PR TITLE
I added some DPLA docs!

### PR DESCRIPTION
**Pull request by apclearing**
Test pull request. Thanks!

--Scott C.

### CODE REVIEW

**Comment by kateefly** [comment]
Minor formatting issue. If there is a lot of descriptive text, it will overlap with the information at the bottom (see below). I would suggest opening a new issue for formatting and wait to merge this pr until the formatting issue can be resolved.

image

**Comment by scottythered** [comment]
Sad to say, this might be a limitation of the underlying template we used -- it keeps all of the "cards" for each doc the same. We can put a limit of how many words can be used, though.

**Comment by scottythered** [comment]
The answer might be to keep the site description short (30 words) and include a README with the uploaded file as a Zip.

**Comment by scottythered** [comment]
(This is essentially what happened here: the text is from a README file in the zip archive. The description text could then be shortened.)

**Comment by kateefly** [comment]
I like that idea. Would we also have to change the form to reflect this?

**Comment by scottythered** [comment]
Yepper -- and in fact, last night I edited it to include description metadata. I was going to wait till this morning to mention it so no one had to get an email blast from me circa midnight, central time.

**Comment by scottythered** [comment]
Give me 10 minutes to fix a coding error and you can re-run the test to see it -- it turns out I screwed up the code when I sent the pull request.

**Comment by scottythered** [comment]
Okay. it should look like this now: 
image

**Comment by kateefly** [comment]
Looked good on my local install! Thanks Scott!

**Pull request merged**
